### ISSUE TITLE
Trading Signals Benchmark

### ISSUE THREAD

**Issue by bennycode** [debut-js/indicators-benchmark#1]
@BusinessDuck it's great that you test the performance of multiple indicator libraries. I've seen that you added [trading-signals](https://github.com/bennycode/trading-signals) to your list of dependencies. Do you plan to also use it in your benchmarks?

**Comment by BusinessDuck** [comment]
hi! sure :) i want to create html page with results of benchmark

**Comment by bennycode** [comment]
Great, I have seen your benchmarks and find it great that people can find the differences in performance: https://github.com/debut-js/Indicators#benchmarks

Out of curiosity: How did you measure the performance for "Stochastic" of my [trading-signals](https://github.com/bennycode/trading-signals/tree/v2.2.0) library? Because I haven't implemented any stochastics.

**Comment by BusinessDuck** [comment]
Hm, stochastic  looks like a mistake =)

**Comment by BusinessDuck** [comment]
@bennycode could you please add trading-signals to all existing suites? I have added an example with EMA [here](https://github.com/debut-js/indicators-benchmark/commit/a98710e3cb6345a1068cadfe29d9856eb844e375)
